<!-- Kalender Availability Lapangan -->
<div class="calendar-availability-widget">
    <div class="cal-header">
        <h3>📅 Kalender Ketersediaan Lapangan</h3>
        <div class="cal-nav">
            <button onclick="prevMonth()" class="cal-btn">← Sebelumnya</button>
            <span id="calendarMonth" class="cal-month-label">Januari 2026</span>
            <button onclick="nextMonth()" class="cal-btn">Selanjutnya →</button>
        </div>
    </div>

    <div class="cal-container">
        <!-- Filter Lapangan -->
        <div class="cal-filter">
            <select id="filterLapangan" onchange="filterByLapangan()">
                <option value="">📍 Semua Lapangan</option>
                @foreach($lapangan as $field)
                    <option value="{{ $field->id }}">{{ $field->namaLapangan }}</option>
                @endforeach
            </select>
        </div>

        <!-- Calendar Grid -->
        <div id="calendarGrid" class="cal-grid">
            <!-- Generated by JavaScript -->
        </div>

        <!-- Legend -->
        <div class="cal-legend">
            <div class="legend-item">
                <span class="legend-color available"></span>
                <span>Tersedia</span>
            </div>
            <div class="legend-item">
                <span class="legend-color booked"></span>
                <span>Terboking</span>
            </div>
            <div class="legend-item">
                <span class="legend-color unavailable"></span>
                <span>Belum Aktif</span>
            </div>
        </div>
    </div>

    <!-- Booking Details Modal -->
    <div id="bookingModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeModal()">&times;</span>
            <h2>📋 Detail Booking</h2>
            <div id="bookingDetails"></div>
        </div>
    </div>
</div>

<style>
    .calendar-availability-widget {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        border-radius: 15px;
        padding: 30px;
        box-shadow: 0 20px 60px rgba(0, 0, 0, 0.15);
        margin: 20px 0;
    }

    .cal-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 25px;
        flex-wrap: wrap;
        gap: 15px;
    }

    .cal-header h3 {
        color: white;
        font-size: 1.5rem;
        font-weight: 700;
        margin: 0;
    }

    .cal-nav {
        display: flex;
        align-items: center;
        gap: 12px;
    }

    .cal-btn {
        padding: 8px 15px;
        background: rgba(255, 255, 255, 0.2);
        color: white;
        border: 2px solid rgba(255, 255, 255, 0.4);
        border-radius: 6px;
        cursor: pointer;
        font-weight: 600;
        transition: all 0.3s ease;
    }

    .cal-btn:hover {
        background: rgba(255, 255, 255, 0.3);
        border-color: white;
        transform: translateY(-2px);
    }

    .cal-month-label {
        color: white;
        font-weight: 600;
        min-width: 140px;
        text-align: center;
    }

    .cal-container {
        background: white;
        border-radius: 12px;
        padding: 20px;
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
    }

    .cal-filter {
        margin-bottom: 20px;
    }

    .cal-filter select {
        width: 100%;
        padding: 12px 15px;
        border: 2px solid #e0e0e0;
        border-radius: 8px;
        font-size: 1rem;
        cursor: pointer;
        transition: all 0.3s ease;
    }

    .cal-filter select:focus {
        border-color: #667eea;
        box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
        outline: none;
    }

    .cal-grid {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));
        gap: 12px;
        margin-bottom: 20px;
    }

    .cal-day {
        aspect-ratio: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        border-radius: 10px;
        border: 2px solid #e0e0e0;
        padding: 10px;
        cursor: pointer;
        transition: all 0.3s ease;
        text-align: center;
        font-size: 0.9rem;
        font-weight: 600;
    }

    .cal-day:hover:not(.unavailable) {
        transform: translateY(-3px);
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
    }

    .cal-day.available {
        background: linear-gradient(135deg, #e8f5e9, #f1f8e9);
        border-color: #4caf50;
        color: #2e7d32;
    }

    .cal-day.available:hover {
        border-color: #2e7d32;
    }

    .cal-day.booked {
        background: linear-gradient(135deg, #ffebee, #fce4ec);
        border-color: #d32f2f;
        color: #c62828;
    }

    .cal-day.booked:hover {
        cursor: pointer;
    }

    .cal-day.unavailable {
        background: #f5f5f5;
        border-color: #bdbdbd;
        color: #9e9e9e;
        cursor: default;
    }

    .cal-day .day-number {
        font-size: 1.1rem;
        font-weight: 700;
    }

    .cal-day .day-status {
        font-size: 0.75rem;
        margin-top: 3px;
        opacity: 0.8;
    }

    .cal-legend {
        display: flex;
        justify-content: center;
        gap: 25px;
        padding-top: 15px;
        border-top: 2px solid #e0e0e0;
    }

    .legend-item {
        display: flex;
        align-items: center;
        gap: 8px;
        font-size: 0.9rem;
        color: #333;
    }

    .legend-color {
        width: 20px;
        height: 20px;
        border-radius: 4px;
        border: 2px solid;
    }

    .legend-color.available {
        background: #e8f5e9;
        border-color: #4caf50;
    }

    .legend-color.booked {
        background: #ffebee;
        border-color: #d32f2f;
    }

    .legend-color.unavailable {
        background: #f5f5f5;
        border-color: #bdbdbd;
    }

    /* Modal Styles */
    .modal {
        display: none;
        position: fixed;
        z-index: 1000;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        animation: fadeIn 0.3s ease;
    }

    .modal.active {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .modal-content {
        background-color: white;
        padding: 30px;
        border-radius: 12px;
        max-width: 500px;
        width: 90%;
        box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
        animation: slideUp 0.3s ease;
    }

    .modal-content h2 {
        color: #667eea;
        margin-bottom: 20px;
    }

    .close {
        color: #aaa;
        font-size: 28px;
        font-weight: bold;
        cursor: pointer;
        float: right;
        transition: color 0.3s ease;
    }

    .close:hover {
        color: #667eea;
    }

    .booking-item {
        background: #f5f7ff;
        border-left: 4px solid #667eea;
        padding: 15px;
        margin: 10px 0;
        border-radius: 6px;
    }

    .booking-item strong {
        color: #667eea;
    }

    @keyframes fadeIn {
        from {
            opacity: 0;
        }
        to {
            opacity: 1;
        }
    }

    @keyframes slideUp {
        from {
            opacity: 0;
            transform: translateY(20px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    @media (max-width: 768px) {
        .cal-header {
            flex-direction: column;
        }

        .cal-nav {
            width: 100%;
            justify-content: space-between;
        }

        .cal-grid {
            grid-template-columns: repeat(auto-fill, minmax(80px, 1fr));
        }

        .cal-legend {
            flex-direction: column;
            gap: 12px;
        }
    }
</style>

<script>
    let currentCalendarMonth = new Date();
    let bookedSlots = {};
    let selectedFilter = '';
    let region = '{{ $region ?? "padang" }}';

    document.addEventListener('DOMContentLoaded', () => {
        renderCalendar();
        loadBookedSlots();
    });

    function renderCalendar() {
        const year = currentCalendarMonth.getFullYear();
        const month = currentCalendarMonth.getMonth();
        const monthNames = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
            'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];

        document.getElementById('calendarMonth').textContent = `${monthNames[month]} ${year}`;

        const firstDay = new Date(year, month, 1);
        const lastDay = new Date(year, month + 1, 0);
        const daysInMonth = lastDay.getDate();
        const startingDayOfWeek = firstDay.getDay();

        let html = '';

        // Day headers
        const dayHeaders = ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'];
        dayHeaders.forEach(day => {
            html += `<div style="text-align: center; font-weight: 700; color: #667eea; padding: 10px 0; grid-column: span 1;">${day}</div>`;
        });

        // Empty cells
        for (let i = 0; i < startingDayOfWeek; i++) {
            html += '<div></div>';
        }

        // Days
        const today = new Date();
        for (let day = 1; day <= daysInMonth; day++) {
            const date = new Date(year, month, day);
            const dateStr = date.toISOString().split('T')[0];
            const dayKey = dateStr;

            let status = 'available';
            let bookingCount = 0;

            if (date < today) {
                status = 'unavailable';
            } else if (dayKey in bookedSlots) {
                status = 'booked';
                bookingCount = bookedSlots[dayKey].length;
            }

            html += `<div class="cal-day ${status}" onclick="showBookingDetails('${dayKey}')">
                <div class="day-number">${day}</div>
                <div class="day-status">${status === 'booked' ? `${bookingCount} booking` : status === 'available' ? '✓ Tersedia' : '✗'}</div>
            </div>`;
        }

        document.getElementById('calendarGrid').innerHTML = html;
    }

    function loadBookedSlots() {
        const params = new URLSearchParams({
            tahun: currentCalendarMonth.getFullYear(),
            bulan: currentCalendarMonth.getMonth() + 1,
            region: region
        });

        if (selectedFilter) {
            params.append('lapangan_id', selectedFilter);
        }

        fetch(`{{ route('api.availability.booked-slots') }}?${params}`)
            .then(r => r.json())
            .then(data => {
                bookedSlots = {};
                data.forEach(slot => {
                    if (!bookedSlots[slot.tanggal]) {
                        bookedSlots[slot.tanggal] = [];
                    }
                    bookedSlots[slot.tanggal].push(slot);
                });
                renderCalendar();
            });
    }

    function showBookingDetails(date) {
        if (!bookedSlots[date]) return;

        let html = `<p><strong>Tanggal:</strong> ${new Date(date).toLocaleDateString('id-ID', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        })}</p>`;

        bookedSlots[date].forEach(booking => {
            html += `
                <div class="booking-item">
                    <div><strong>Lapangan:</strong> ${booking.lapangan_nama}</div>
                    <div><strong>Pemesan:</strong> ${booking.nama_pemesan}</div>
                    <div><strong>Jam:</strong> ${booking.jam_mulai} - ${booking.jam_selesai}</div>
                </div>
            `;
        });

        document.getElementById('bookingDetails').innerHTML = html;
        document.getElementById('bookingModal').classList.add('active');
    }

    function closeModal() {
        document.getElementById('bookingModal').classList.remove('active');
    }

    function filterByLapangan() {
        selectedFilter = document.getElementById('filterLapangan').value;
        loadBookedSlots();
    }

    function prevMonth() {
        currentCalendarMonth = new Date(currentCalendarMonth.getFullYear(), currentCalendarMonth.getMonth() - 1);
        loadBookedSlots();
    }

    function nextMonth() {
        currentCalendarMonth = new Date(currentCalendarMonth.getFullYear(), currentCalendarMonth.getMonth() + 1);
        loadBookedSlots();
    }

    // Close modal when clicking outside
    window.onclick = function (event) {
        const modal = document.getElementById('bookingModal');
        if (event.target === modal) {
            modal.classList.remove('active');
        }
    }
</script>
